### ISSUE TITLE
CheckList do  que ainda precisamos implementar (ou corrigir)

### ISSUE THREAD

**Issue by ntak1** [tainaturella/AwesomeMix#2]
**Conceitos que devem ser abordados**
- [x] Classes, variáveis e métodos

- [x]   Visibilidade

- [x]  Herança. 

- [ ]  Entrada e saída de dados (poderiamos fazer o teste de funcionalidades com dados de entrada do usuario).

- [x]   Variáveis e Métodos estáticos

- [x]   Arrays

- [x]   Enumeração (Precisamos Alterar a classe Musica para ter o estilo musical como atributo e criamos um enum para este).

- [x]  Além disso, utilizaremos diagramas de classe UML para representação do projeto de classes.

**O que precisamos entregar**

- [x]  Um resumo descrevendo o sistema a ser projetado

- [x]   O levantamento de todas as funções que devem ser executadas no sistema (por exemplo: cadastrar
usuário, pedir carona, orferecer carona, adicionar membro ao grupo,  etc.) Poderiamos, cada um responsavel por uma classe, descrevermos o funcionamento dela. Depois fazemos um apanhado geral.

- [x]   A estrutura das classes que resolve o problema abordado incluindo:

- [x] Atributos

- [x] Métodos (construtores, acesso, métodos gerais)

- [x]  Relacionamentos (isso quer dizer classe associativa/relacionamento bidirecional ???)

- [x]   A implementação das classes

- [x]  O teste das funcionalidades do sistema. Aqui provavelmente seria a Main com a instanciação dos objetos, etc.

- [x] Um indicador de quais funcionalidades foram implementadas nesta fase
