### ISSUE TITLE
CheckList Projeto 2: o que deve obrigatóriamente estar presente

### ISSUE THREAD

**Issue by ntak1** [tainaturella/AwesomeMix#4]
Os seguintes conceitos deverão ser adequadamente incorporados no sistema a ser desenvolvido, além
daqueles do projeto 1:

- [x] Relacionamentos (associação, agregação ou composição): o sistema deve contemplar relacionamentos; 

- [x] Interfaces e Classes Abstratas: ao menos uma interface deve ser implementada e uma classe
abstrata;

- [x]  Interface Gráfica: o sistema deverá ser controlado através de uma interface gráfica. Aqueles que
desejem construir uma interface web ou mobile estão autorizados;

- [ ] Tratamento de exceção: o sistema deve tratar exceções com, ao menos, uma exceção definida
pelo grupo;

- [ ] Arquivos (gravação e leitura): o sistema deve realizar a leitura e gravação em arquivos de elementos de interesse ao projeto.

- [ ] Além disso, utilizaremos diagramas de classe UML para representação do projeto de classes.

- [ ] Fazer diagrama do banco de dados.
